repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: ["--fix"]  # Uses config from pyproject.toml
        language_version: python3.11
        files: ^src/.*\.py$
      - id: ruff-format
        language_version: python3.11
        files: ^src/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-openpyxl", "types-requests", "types-psycopg2"]
        language_version: python3.11
        files: ^src/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
